embedder:
  provider: "openai"
  config:
    model: "text-embedding-3-small"
    dimension: 384

long_term_memory:
  enabled: false
  external: false
  connection_string: "postgresql://postgres:your_password@localhost:5432/cognition_db"

short_term_memory:
  enabled: false
  external: false
  host: "localhost"
  port: 8000
  collection_name: "short_term"

entity_memory:
  enabled: false
  external: false
  host: "localhost"
  port: 8000
  collection_name: "entities"
