analysis_task:
  description: >
    "Analyze the meeting notes: {notes_subject} from the Knowledge Source. 
    Format it into structured meeting notes with the following sections: Date, Participants,
    Goals, Discussion topics (with timestamps), Action items, and Decisions."
  expected_output: "Structured meeting notes following the required template format"
  agent: analyzer

doc_generation_task:
  description: >
    "Take the structured meeting notes: {notes_subject} from the Knowledge Source. 
    Save them as a markdown file in the home directory. 
    Ensure the formatting is clean and professional, with an appropriate filename 
    based on the meeting date and topic."
  expected_output: "Confirmation of successful file creation with the file path"
  agent: doc_generation_agent
