version: "1.0"
environment: "development"

# Tool Service Configuration
tool_services:
  - name: "primary_service"
    enabled: true
    base_url: "http://localhost:8000"
    endpoints:
      - path: "/tools"
        method: "GET"
        description: "Fetches available tools"

# Global Tool Settings
settings:
  cache:
    enabled: false
    ttl: 3600 # Cache TTL in seconds
    max_size: 1000 # Maximum number of cached results

  retry:
    max_attempts: 3
    backoff_factor: 0.5

  validation:
    schema_validation: true
    response_timeout: 30

# Default Tool Parameters
default_parameters:
  timeout: 10
  max_tokens: 1000
